# This is a basic workflow to help you get started with Actions

name: My-GitHubActions
env:
 APPLICATION_NAME : "MyFlask"
 DEPLOY_PACKAGE_NAME : "flask-deploy-ver-${{github.sha }}"


 on: 
    push:
      branches: 
      - master
    
jobs:
     my-testing:
         runs-on: ubuntu-latest
         steps:
          - name: Print Hello in Testing
            run : echo "Hello from Testing job"
            
          - name: Execure few commands
            run :
              echo "Message 1"
              echo "Message 2"
              echo "Application name ${{ env.APPLICATION_NAME }}"
              
          - name: List current folder
            run: ls -la
          
          - name: Git clone my repo
            uses: actions/checkout@v1
           
          - name: List current folder
            run: ls -la
     my_deploy:
       runs-on: ubuntu-latest
       needs: [my_testing]
       env: 
         VAR1:"This is Variable1"
         VAR1:"This is Variable1"
         
       steps:
        - name: Print Hello in Deploy
          run: echo "Hello from Deploy job" 
          
        - name : Print Vars
           run : |
             echo "Var1 = ${{ env.VAR1 }}"
             echo "Var2 = ${{ env.VAR2 }}"
             echo "Var3 = $LOCAL_VAR"
           env:
            LOCAL_VAR: "Suuper local variable"
            
        - name : aws test
          run : aws --version
          
        - name : zip test
          run : zip --version
         
